1-Module. Tasks 3-5
js-tasks-ru/jsbasic-20230911_julia-kurianova pull request #3
Opened 2023-09-17 18:38 UTC by judy99

2023-09-17 18:39 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-18 09:34 UTC, SinimaWath requested changes

2023-09-18 09:34 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
Давай упростим без if `return str.includes(spamWord1) || str.includes(spamWord2)`

2023-09-18 16:52 UTC, judy99 commented on 1-module/4-task/index.js
> +  return false;
готово

2023-09-18 16:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-19 16:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-19 17:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-09-20 12:57 UTC, SinimaWath approved these changes

2023-09-20 12:58 UTC, merged